data:
  bvp_agg: sum
  data_dir: "C:\\Tue\\Master\\Jaar_2\\graduation\\code\\DiGR-RL\\data"
  dataset_type: single_user
  downsample_multiplier: 100
  amp_pipeline:
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  phase_pipeline:
    - "phase_unwrap"
    - "phase_filter"
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  transformation: rp
debug:
  is_debug: false
  offline: false
  on_cpu: false
embed:
  agent_type: ppo
  reward_function: combined
  policy: do_nothing
  start_epoch: 35
  epochs: 2
encoder:
  activation_fn: leaky
  dropout: 0.18
  initial_kernel_size: 7
  latent_dim: 60
  type: CNN
mt:
  d_predictor_activation_fn: gelu
  d_predictor_dropout: 0.26
  d_predictor_num_layers: 4
  predictor_activation_fn: selu
  predictor_dropout: 0.28
  predictor_num_layers: 4
agent:
  ent_coef: 0.094
  learning_rate: 0.000312
  buffer_size: 50000
  gradient_steps: 16
  batch_size: 512
  learning_starts: 1600
  factor: 2
  threshold: 10
  sequential: True
optim_loss:
  alpha: 0.000255
  beta: 0.5
  lr: 0.000911
  optimizer: adam
train:
  batch_size: 32
  checkpoint_dir: ../Checkpoints
  epochs: 100
  ui: tqdm
  tuning: False
