data:
  bvp_agg: sum
  data_dir: "C:\\Tue\\Master\\Jaar_2\\graduation\\code\\DiGR-RL\\data"
  dataset_type: single_user
  downsample_multiplier: 100
  amp_pipeline:
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  phase_pipeline:
    - "phase_unwrap"
    - "phase_filter"
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  transformation: gaf
debug:
  is_debug: false
  offline: false
  on_cpu: false
embed:
  agent_type: ppo
  reward_function: exploration_driven
  policy: hybrid
  start_epoch: 35
  epochs: 2
encoder:
  activation_fn: gelu
  dropout: 0.25
  latent_dim: 50
  type: ViT
  base_channels: 64
  patch_size: 4
  vit_depth: 4
  vit_heads: 4
mt:
  d_predictor_activation_fn: leaky
  d_predictor_dropout: 0.067
  d_predictor_num_layers: 6
  predictor_activation_fn: selu
  predictor_dropout: 0.11
  predictor_num_layers: 4
agent:
  ent_coef: 0.018
  learning_rate: 5.28e-05
  buffer_size: 20000
  gradient_steps: 16
  batch_size: 512
  learning_starts: 3600
  factor: 3
  threshold: 10
  sequential: True
optim_loss:
  alpha: 3.63e-4
  beta: 0.37
  lr: 6.29e-4
  optimizer: adam
train:
  batch_size: 32
  checkpoint_dir: ../Checkpoints
  epochs: 100
  ui: tqdm