data:
  bvp_agg: sum
  data_dir: "C:\\Tue\\Master\\Jaar_2\\graduation\\code\\DiGR-RL\\data"
  dataset_type: single_user
  downsample_multiplier: 100
  amp_pipeline:
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  phase_pipeline:
    - "phase_unwrap"
    - "phase_filter"
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  transformation: rp
debug:
  is_debug: false
  offline: false
  on_cpu: false
embed:
  agent_type: ppo
  reward_function: environment_adaptation
  policy: hybrid
  start_epoch: 35
  epochs: 2
encoder:
  activation_fn: relu
  dropout: 0.069
  initial_kernel_size: 5
  latent_dim: 30
  type: DenseNet
  normalization: False
  init_channels: 64
  growth_rate: 56
mt:
  d_predictor_activation_fn: relu
  d_predictor_dropout: 0.15
  d_predictor_num_layers: 6
  predictor_activation_fn: selu
  predictor_dropout: 0.24
  predictor_num_layers: 3
agent:
  ent_coef: 0.064
  learning_rate: 7.09e-05
  buffer_size: 50000
  gradient_steps: 16
  batch_size: 512
  learning_starts: 1600
  factor: 4
  threshold: 10
  sequential: True
optim_loss:
  alpha: 0.000144
  beta: 0.096
  lr: 0.000745
  optimizer: adam
train:
  batch_size: 32
  checkpoint_dir: ../Checkpoints
  epochs: 100
  ui: tqdm
