data:
  bvp_agg: sum
  bvp_pipeline: 0
  data_dir: "C:\\Tue\\Master\\Jaar_2\\graduation\\code\\own_approach\\data"
  dataset_type: single_user
  downsample_multiplier: 100
  amp_pipeline:
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  phase_pipeline:
    - "phase_unwrap"
    - "phase_filter"
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  transformation: rp
debug:
  is_debug: false
  offline: false
  on_cpu: false
embed:
  agent_type: ppo
  reward_function: environment_adaptation
  policy: hybrid
  start_epoch: 101
  value_type: probability-measure
  epochs: 2
encoder:
  activation_fn: relu
  dropout: 0.06949780642398673
  initial_kernel_size: 5
  latent_dim: 30
  type: DenseNet
  normalization: False
  init_channels: 64
  growth_rate: 56
mt:
  d_predictor_activation_fn: relu
  d_predictor_dropout: 0.14592265699637819
  d_predictor_num_layers: 6
  predictor_activation_fn: selu
  predictor_dropout: 0.2426637792205302
  predictor_num_layers: 3
optim_loss:
  alpha: 0.00014467646280371654
  beta: 0.09646717560116949
  lr: 0.0007451656570213542
  optimizer: adam
train:
  batch_size: 32
  checkpoint_dir: /home2/xvreewij/Checkpoints
  epochs: 100
  ui: tqdm
